### ISSUE TITLE
Add UTF-8 support in code area

### ISSUE THREAD

**Issue by AlexxNB** [aporto/mariamole#41]
I get "?????" instead russian letters, when I tried write comments in the code.  
Try to paste this "тестовый текст" in the code area.

![image](https://cloud.githubusercontent.com/assets/10389013/6002364/a77a5a44-ab03-11e4-86e2-326a7417b3bc.png)

**Comment by aporto** [comment]
Yes, I saw the "??????". Gonna need some days to investigate this.

**Comment by aporto** [comment]
Fixed. That was as simple as adding "setUtf8(true);" at the Editor constructor.

**Comment by AlexxNB** [comment]
Just tried it. Works good. 
Thank you!
